/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktest_NDKUtils */

#ifndef _Included_com_example_ndktest_NDKUtils
#define _Included_com_example_ndktest_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktest_NDKUtils
 * Method:    invokeCmethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktest_NDKUtils_invokeCmethod
  (JNIEnv *env, jobject obj);

/*
 * Class:     com_example_ndktest_NDKUtils
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ndktest_NDKUtils_grayProc
  (JNIEnv *env, jclass clazz, jintArray buf, jint w, jint h, jint nW, jint nH);

#ifdef __cplusplus
}
#endif
#endif
